apiVersion: v1
kind: Service
metadata:
  name: {{ include "laravel.fullname" . }}
  labels:
    {{- include "laravel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8000
      nodePort: 30080
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    {{- include "laravel.selectorLabels" . | nindent 4 }}
