apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-nginx
data:
  nginx.conf: |
    server {
      listen       80;
      listen       [::]:80;
      server_name  localhost;
      root /var/www/html/public;
      proxy_set_header Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header X-NginX-Proxy true;
      location / {
        try_files $uri /index.php$is_args$args;
        proxy_connect_timeout 300;
        proxy_send_timeout 300;
        proxy_read_timeout 300;
        send_timeout 300;
      }
      location ~ .php$ {
        fastcgi_pass unix:/sock/php-fpm.sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_pass_request_headers on;
        fastcgi_read_timeout 300;
        include fastcgi_params;
      }
    }