apiVersion: apps/v1
kind: Deployment
metadata:
  name: was-deployment
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      volumes:
        - name: nginx-php-sock
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: configmap-nginx
        - name: php-conf
          configMap:
            name: configmap-php
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
        - name: laravel
          image: localhost:5001/laravel:0.0.4
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: php-conf
              mountPath: /usr/local/etc/php-fpm.d/zzz.conf
              subPath: zzz.conf