apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-laravel
  labels:
    app: was
spec:
  replicas: 1
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      volumes:
        - name: nginx-php-sock
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: configmap-nginx
        - name: php-conf
          configMap:
            name: configmap-php
        - name: nginx-php-static-resource
          emptyDir: {}
        {{ if .Values.localMount }}
        - name: local-laravel-code
          hostPath:
            path: /app/www
        {{ end }}
      initContainers:
        - name: init-volume
          image: localhost:5001/laravel:0.0.6
          command: ['sh', '-c', 'cp -r /var/www/html/public/* /usr/share/nginx/html/public']
          volumeMounts:
            - name: nginx-php-static-resource
              mountPath: /usr/share/nginx/html/public
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: nginx-php-static-resource
              mountPath: /usr/share/nginx/html/public
        - name: laravel
          image: localhost:5001/laravel:0.0.6
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: php-conf
              mountPath: /usr/local/etc/php-fpm.d/zzz.conf
              subPath: zzz.conf
            {{ if .Values.localMount }}
            - name: local-laravel-code
              mountPath: /var/www/html
            {{ end }}