apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-nginx-laravel
  labels:
    app: was
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # 배포 중에도 죽은 놈은 0명이어야 한다 (서비스 유지)
      maxSurge: 1        # 새 파드 1개를 먼저 만들고 시작해라
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      volumes:
        - name: nginx-php-sock
          emptyDir: {}
        - name: nginx-conf
          configMap:
            name: configmap-nginx
        - name: php-conf
          configMap:
            name: configmap-php
        - name: nginx-php-static-resource
          emptyDir: {}
        - name: secret-volume
          secret:
            secretName: quickstart-es-http-certs-internal
        {{ if .Values.localMount }}
        - name: local-laravel-code
          hostPath:
            path: /app/www
        {{ end }}
      initContainers:
        - name: init-volume
          image: localhost:5001/laravel:latest
          command: ['sh', '-c', 'cp -r /var/www/html/public/* /usr/share/nginx/html/public']
          volumeMounts:
            - name: nginx-php-static-resource
              mountPath: /usr/share/nginx/html/public
      containers:
        - name: nginx
          image: nginx:1.26.0
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: nginx-conf
              mountPath: /etc/nginx/conf.d
            - name: nginx-php-static-resource
              mountPath: /usr/share/nginx/html/public
          resources:
            requests:
              cpu: 1m
              memory: 40Mi
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30    # 30 * 2s = 60초 동안 기다림
            periodSeconds: 2
          readinessProbe:
            httpGet:
              path: /  # 혹은 /healthcheck
              port: 80
            initialDelaySeconds: 0   # startupProbe 이후
            periodSeconds: 30        # periodSeconds초 간격으로 찌름
            timeoutSeconds: 2        # 2초 이상 답변 없으면 고장난 것으로 간주
            successThreshold: 1      # 1번 성공하면 OK
            failureThreshold: 3      # 3번 실패하면 고장난 걸로 간주
          livenessProbe:
            httpGet:
              path: /  # 혹은 /healthcheck
              port: 80
            initialDelaySeconds: 0   # startupProbe 이후
            periodSeconds: 30        # periodSeconds초 간격으로 찌름
            timeoutSeconds: 2        # 2초 이상 답변 없으면 고장난 것으로 간주
            successThreshold: 1      # 1번 성공하면 OK
            failureThreshold: 3      # 3번 실패하면 고장난 걸로 간주

            # 종료 지연 (GCP LB 갱신될 때까지 버티기)
          lifecycle:
            preStop:
              exec:
                command: [ "/bin/sh", "-c", "sleep 10" ]
        - name: laravel
          image: localhost:5001/laravel:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          volumeMounts:
            - name: nginx-php-sock
              mountPath: /sock
            - name: php-conf
              mountPath: /usr/local/etc/php-fpm.d/zzz.conf
              subPath: zzz.conf
            - name: secret-volume
              mountPath: "/etc/secret-volume"
              readOnly: true
            {{ if .Values.localMount }}
            - name: local-laravel-code
              mountPath: /var/www/html
            {{ end }}
          env:
            - name: ELASTIC_SEARCH_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          resources:
            requests:
              cpu: 5m
              memory: 200Mi
