apiVersion: v1
kind: Service
metadata:
  name: service-was
spec:
  type: NodePort
  selector:
    app: was
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080